"use client";

import { ContentCalendarItem, ContentType, Channel } from "@/types/bot";

const TYPE_LABELS: Record<ContentType, string> = {
  "product-launch": "Product Launch",
  "partner-launch": "Partner Launch",
  "thought-leadership": "Thought Leadership",
  other: "Other",
};

const TYPE_STYLES: Record<ContentType, string> = {
  "product-launch":
    "bg-indigo-900/50 text-indigo-300 border border-indigo-700/60",
  "partner-launch":
    "bg-emerald-900/50 text-emerald-300 border border-emerald-700/60",
  "thought-leadership":
    "bg-amber-900/50 text-amber-300 border border-amber-700/60",
  other: "bg-zinc-800 text-zinc-300 border border-zinc-700",
};

const CHANNEL_STYLES: Record<Channel, string> = {
  "Email only": "text-blue-400",
  "X only": "text-sky-400",
  "LinkedIn only": "text-cyan-400",
  "X + LinkedIn": "text-teal-400",
  "Email + X": "text-violet-400",
  "Email + LinkedIn": "text-purple-400",
  "All channels": "text-rose-400",
};

interface ContentCalendarProps {
  items: ContentCalendarItem[];
}

export default function ContentCalendar({ items }: ContentCalendarProps) {
  return (
    <div className="mt-8 rounded-xl border border-zinc-800 bg-zinc-900 overflow-hidden">
      {/* Header */}
      <div className="px-6 py-4 border-b border-zinc-800 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <span className="text-xl" aria-hidden="true">
            📅
          </span>
          <div>
            <h2 className="text-sm font-semibold text-white">
              Content Calendar
            </h2>
            <p className="text-xs text-zinc-500 mt-0.5">
              {items.length} weeks planned · Generated by Content Strategist
            </p>
          </div>
        </div>

        {/* Legend */}
        <div className="hidden sm:flex items-center gap-4 text-[10px] text-zinc-500">
          {(Object.keys(TYPE_LABELS) as ContentType[]).map((t) => (
            <span key={t} className="flex items-center gap-1.5">
              <span
                className={`inline-block w-2 h-2 rounded-sm ${TYPE_STYLES[t].split(" ")[0]}`}
              />
              {TYPE_LABELS[t]}
            </span>
          ))}
        </div>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-xs">
          <thead>
            <tr className="border-b border-zinc-800 text-left">
              <th className="px-4 py-3 font-medium text-zinc-500 w-10">Wk</th>
              <th className="px-4 py-3 font-medium text-zinc-500 w-28">
                Date
              </th>
              <th className="px-4 py-3 font-medium text-zinc-500">
                Content Idea
              </th>
              <th className="px-4 py-3 font-medium text-zinc-500 w-40">
                Type
              </th>
              <th className="px-4 py-3 font-medium text-zinc-500 w-36">
                Channels
              </th>
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr
                key={item.week}
                className="border-b border-zinc-800/50 last:border-0 hover:bg-zinc-800/30 transition-colors"
              >
                <td className="px-4 py-3 text-zinc-500 font-mono">
                  {item.week}
                </td>
                <td className="px-4 py-3 text-zinc-400 font-mono whitespace-nowrap">
                  {item.date}
                </td>
                <td className="px-4 py-3">
                  <p className="text-white font-medium mb-0.5">{item.title}</p>
                  <p className="text-zinc-500 leading-relaxed">
                    {item.description}
                  </p>
                </td>
                <td className="px-4 py-3">
                  <span
                    className={`inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium ${TYPE_STYLES[item.type]}`}
                  >
                    {TYPE_LABELS[item.type]}
                  </span>
                </td>
                <td
                  className={`px-4 py-3 font-medium whitespace-nowrap ${CHANNEL_STYLES[item.channels]}`}
                >
                  {item.channels}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
